### ISSUE TITLE
Behaves unexpectedly when I try to delete characters within placeholder

### ISSUE THREAD

**Issue by alexandis** [digitalBush/jquery.maskedinput#345] opened 2015-12-24 17:53 UTC
For instance, i have this mask:
(999) 999-9999
I neither can remove second and third character from country code - it always takes next one from number.
Nor I can define pattern to allow range of characters for country code. Tried mask definition, seems it only understand pattern for one characters.
What to do? I didn't get something??

**Comment by kaljak** [comment] 2016-01-19 19:59
Which device are you using?
Do you have any fiddle where this can be reproduced?
--> Works fine for me :)

**Comment by alexandis** [comment] 2016-01-20 07:33
Oh,
alas, I don't use this plugin anymore...
But I've read the mask is not intended for variable number of characters (this one and similar plugins). So I gave up and decided to use a plain numeric format, which I intercept with paste event and handle via regex (so i can copy any other formats - with dashes, spaces, etc.)

**Comment by digitalBush** [comment] 2016-03-23 22:32
Just catching up. Closing this issue since you figured out a resolution.

**Closed** 2016-03-23 22:31 UTC
